import glob
# These are just here temporarily

Import('env')

CUTBuilder = Builder(action="tools/cutgen $SOURCES -o $TARGET")
env['BUILDERS']['CUT'] = CUTBuilder



#### TARGET:  CUT Tests ###

test_cases = glob.glob("*_test.c")

Program(target="#tools/cutgen", 
       source=["#tools/cutgen.c"], 
       CCFLAGS='-D__LINUX__')

env.CUT(target="testrunner.c", source=test_cases)
Program(target="#build/testrunner", 
    source=test_cases + ["testrunner.c",  "#build/libclaro-graphics"+env['SHLIBSUFFIX'], "#build/libclaro-base"+env['SHLIBSUFFIX']])


Alias("all", ["#tools/cutgen", "#build/testrunner"])
Default( 'all' )
